apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.extensions.example.com
spec:
  scope: Namespaced
  group: extensions.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRepo: # repositorio GitHub
                  type: string
                puerto: # puerto NodePort del servidor
                  type: integer
  names:
    kind: Website
    singular: website
    plural: websites
